const CACHE="eldanor-v5.3.1";
const CORE=["./", "./?v=53", "./icons-void-v42.webp", "./backgrounds-paper-v42.webp", "./map-eldanor-v42.png", "./icons-fire-v42.webp", "./icons-coin-v42.webp", "./icons-helmet-v42.webp", "./styles-v53.css?v=53", "./icons-dice-v42.webp", "./icons-quest-v42.webp", "./icons-shield-v42.webp", "./icons-map-v42.webp", "./backgrounds-darkframe-v42.webp", "./icons-compass-v42.webp", "./icons-campfire-v42.webp", "./banners-map-v42.webp", "./icons-sword-v42.webp", "./icons-lightning-v42.webp", "./icons-crown-v42.webp", "./icons-skull-v42.webp", "./manifest.webmanifest", "./icons-journal-v42.webp", "./icons-rune-v42.webp", "./app-v53.js?v=53", "./icon-codex-v53-180.png", "./icon-codex-v53-192.png", "./banners-dice-v42.webp", "./icons-runestone-v42.webp", "./banners-journal-v42.webp", "./icons-castle-v42.webp", "./icons-portal-v42.webp", "./icons-potion-v42.webp", "./backgrounds-cosmic-v42.webp", "./icons-hourglass-v42.webp", "./icons-gear-v42.webp", "./icon-codex-v53-512.png", "./icons-paw-v42.webp", "./icons-backpack-v42.webp", "./help-hp-v53.webp", "./help-ac-v53.webp", "./help-init-v53.webp", "./help-speed-v53.webp", "./help-prof-v53.webp", "./help-level-v53.webp", "./help-str-v53.webp", "./help-dex-v53.webp", "./help-con-v53.webp", "./help-int-v53.webp", "./help-wis-v53.webp", "./help-cha-v53.webp", "./help-skill-v53.webp", "./help-attack-v53.webp", "./help-ability-v53.webp", "./help-adv-v53.webp", "./index.html", "./portraits/mjolnir-v42.webp", "./portraits/thalen-v42.webp", "./portraits/borealis-v42.webp", "./portraits/kaelen-v42.webp", "./portraits/lyra-v42.webp", "./portraits/xyra-v42.webp", "./portraits/serenya-v42.webp"];
const ACTIVE_CACHE="eldanor-v5.8.0";
const V55_ASSETS=["./?v=58","./styles-v53.css?v=58","./app-v53.js?v=58","./map-eldanor-v55.webp","./background-dice-chamber-v55.webp","./background-parchment-v55.webp","./dice-w4-v55.webp","./dice-w6-v55.webp","./dice-w8-v55.webp","./dice-w10-v55.webp","./dice-w12-v55.webp","./dice-w20-v55.webp"];
const CORE_V55=[...CORE.filter(x=>!["./?v=53","./styles-v53.css?v=53","./app-v53.js?v=53","./map-eldanor-v42.png","./backgrounds-paper-v42.webp"].includes(x)),...V55_ASSETS];
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(ACTIVE_CACHE).then(c=>c.addAll(CORE_V55)))});
self.addEventListener("activate",e=>e.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==ACTIVE_CACHE).map(k=>caches.delete(k))))])));
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;e.respondWith(fetch(e.request,{cache:"no-store"}).then(r=>{if(r&&r.status===200){const cp=r.clone();caches.open(ACTIVE_CACHE).then(c=>c.put(e.request,cp))}return r}).catch(()=>caches.match(e.request).then(r=>r||caches.match("./index.html"))))});


